In [1]:
import pandas as pd
import matplotlib as plt

In [23]:
df = pd.read_csv("results/results_2022-5-17-13-36-29.csv")
df.drop(df.columns[0], axis=1, inplace=True)
df.drop(df.columns[-1], axis=1, inplace=True)
df.drop(df.columns[-1], axis=1, inplace=True)
resultcolumns = ["Test Accuracy STOP",'Basic Preprocessing', "Expand Contractions", "Grammar Correction", "Simplify Negotiations", "Lemmatize", "Remove Stop Words_ver2", "Length of Sentence", "Train Accuracy STOP", "Train Loss STOP", "Test Loss STOP"]
res = df[resultcolumns]
res.rename(columns = {'Basic Preprocessing':'BP', 'Expand Contractions':'EC', "Grammar Correction":"GC", "Simplify Negotiations":"SN", "Lemmatize":"Lmtz", "Remove Stop Words-ver2":"rmStpWrds"}, inplace = True)
res

,Test Accuracy STOP,BP,EC,GC,SN,Lmtz,Remove Stop Words_ver2,Length of Sentence,Train Accuracy STOP,Train Loss STOP,Test Loss STOP
0,0.431673,1,0,1,0,0,1,40,0.236,11.784663,8.766422
1,0.431673,1,1,0,1,0,0,40,0.236,11.784660,8.766422
2,0.431673,1,1,1,1,0,1,40,0.236,11.784690,8.766422
3,0.568127,1,1,1,0,0,1,40,0.762,0.537670,0.805082
4,0.577031,1,1,0,1,0,1,40,0.769,0.530650,0.799561
5,0.578231,1,0,1,1,0,1,40,0.793,0.488759,0.763315
6,0.580332,1,0,0,1,0,1,40,0.796,0.505128,0.777870
7,0.586034,1,1,0,0,0,1,40,0.775,0.530483,0.825629
8,0.587035,1,0,0,0,0,1,40,0.795,0.506231,0.773721
9,0.601541,1,0,1,0,0,0,40,0.807,0.482596,0.745753
10,0.605242,1,1,0,0,0,0,40,0.804,0.485812,0.742799
11,0.609344,1,1,1,0,0,0,40,0.792,0.504578,0.723900
12,0.611845,1,1,1,1,0,0,40,0.821,0.437696,0.734119
13,0.619048,1,0,0,1,0,0,40,0.788,0.516308,0.713737
14,0.705082,1,0,1,1,0,0,40,0.931,0.176262,0.636511
15,0.764106,1,0,0,0,0,0,40,0.961,0.119621,0.680420

   Model Name  Basic Preprocessing
0         RNN                    1
1         RNN                    1
2         RNN                    1
3         RNN                    1
4         RNN                    1
5         RNN                    1
6         RNN                    1
7         RNN                    1
8         RNN                    1
9         RNN                    1
10        RNN                    1
11        RNN                    1
12        RNN                    1
13        RNN                    1
14        RNN                    1
15        RNN                    1